apiVersion: v1
kind: Service
metadata:
  name: demo-api-core
  namespace: insurance-development
  labels:
    app: demo-api-core
    version: "1.0"
    environment: development
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: demo-api-core
    version: "1.0"
    environment: development
